### ISSUE TITLE
pyinstaller is failing according to the repository badge

### ISSUE THREAD

**Issue by matkoniecz** [hussain5416/Extract_Links#38]
![screen03](https://user-images.githubusercontent.com/899988/188648251-0ea6fa28-2e2d-4f14-b67c-b686858ec955.png)

**Comment by sayyid5416** [comment]
This issue has been investigated.

Issue is not with this repository (Links extractor). It's a problem in the GitHub action which I use to automatically create the executable for Links Extractor. Action is failing because it doesn't support latest python version 10.4, and my code is based on python 10.4

**Comment by sayyid5416** [comment]
This issue has been investigated.

Issue is not with this repository (Links extractor). It's a problem in the GitHub action which I use to automatically create the executable for Links Extractor. Action is failing because it doesn't support latest python version which I'm using for my code.

**Comment by sayyid5416** [comment]
If you want **executable**, You can download the zip file from the [latest release](https://github.com/sayyid5416/Links-Extractor/releases/latest).

I manually created it using PyInstaller, because automatic creation was failing.
